import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header} from "../components/header";
import { Menu } from "@/components/menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Menu />
        <div className="main-content">
          <Header /> 
          <main className="content-area">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
